DROP DATABASE IF EXISTS arnoldi;
CREATE DATABASE arnoldi;
USE arnoldi;
CREATE TABLE ASSICURATORE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255)

);
CREATE TABLE ASSICURATO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255)

);

CREATE TABLE POLIZA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIZIONE VARCHAR(255),
    PREZZO_PREMIO INT     
);
CREATE TABLE CONTRATTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATA_INIZIO VARCHAR(255),
    DATA_FINE VARCHAR(255),
    POLIZA_ID INT,
    ASSICURATORE_ID INT,
    ASSICURATO_ID INT,
    FOREIGN KEY (POLIZA_ID) REFERENCES POLIZA(ID),
    FOREIGN KEY (ASSICURATORE_ID) REFERENCES ASSICURATORE(ID),
    FOREIGN KEY (ASSICURATO_ID) REFERENCES ASSICURATO(ID)
);
INSERT INTO ASSICURATORE (NOME) VALUES ('INA');
INSERT INTO ASSICURATORE (NOME) VALUES ('Sara');
INSERT INTO ASSICURATORE (NOME) VALUES ('Allianz');
INSERT INTO ASSICURATORE (NOME) VALUES ('Unipol');
INSERT INTO ASSICURATO (NOME) VALUES ('Tizio');
INSERT INTO ASSICURATO (NOME) VALUES ('Caio');
INSERT INTO ASSICURATO (NOME) VALUES ('Sempronio');
INSERT INTO ASSICURATO (NOME) VALUES ('Calpurnio');
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione Responsabilità Civile Automezzo',300);
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione danneggiamento da grandine dell’automezzo',120);
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione Responsabilità Civile Motociclo',140);
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione a copertura danni verso terzi, abitazioni',220);
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione a copertura danni abitazioni',290);
INSERT INTO POLIZA (DESCRIZIONE,PREZZO_PREMIO) VALUES ('Assicurazione a copertura danni abitazioni',290);
INSERT INTO CONTRATTO (DATA_INIZIO,DATA_FINE,POLIZA_ID,ASSICURATORE_ID,ASSICURATO_ID) VALUES ('2020-01-01','2023-01-01'1,1,1);
INSERT INTO CONTRATTO (DATA_INIZIO,DATA_FINE,POLIZA_ID,ASSICURATORE_ID,ASSICURATO_ID) VALUES ('2020-01-01','2023-01-01'1,2,2);
INSERT INTO CONTRATTO (DATA_INIZIO,DATA_FINE,POLIZA_ID,ASSICURATORE_ID,ASSICURATO_ID) VALUES ('2020-01-01','2023-01-01'1,3);
INSERT INTO CONTRATTO (DATA_INIZIO,DATA_FINE,POLIZA_ID,ASSICURATORE_ID,ASSICURATO_ID) VALUES ('2020-01-01','2023-01-01'1,4,4);
